name: Get Free

on:
  workflow_dispatch:
  schedule:
    - cron: '1 0,12 * * *'
  watch:
    types: [started]

jobs:
  GETFREE:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: checkout actions
      uses: actions/checkout@v2
    - name: Set python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade requests
      
    - name: Get infor
      run: python 91porn.py

    - name: Get ENV
      env:
        URL91: ${{ secrets.URL91 }}
        run: echo $URL91





